
name: Postman Tests

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install    Newman
        run: npm install -g newman
      - name: Run Postman Tests
        run: newman run korapay_postman_collection.json -e korapay_postman_environment.json junit #--report-html-export TestResult.html --report-junit-export TestResult.xml
      # - name: print Report
      #   run: echo Success --guess -f json -o TestResult.json
